# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LoBntnZIpoasOEx56DNuaqEdgJXlV5es

# HW3: Classification
In this exercise, you will fine-tune a pre-trained convolutional neural network (CNN) for image classification. The dataset contains chess positions labeled as either 'insufficient material' or 'sufficient material.'
Make sure to upload the provided dataset to Google Colab or Google Drive before running the code.

## Package Imports
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import models, transforms
from torch.utils.data import DataLoader, Dataset
from datasets import load_dataset
import os
from PIL import Image

torch.manual_seed(0)

"""## Dataset

Try uploading the dataset directly into colab. If that that fails, you can download the data into your Google Drive and then mount your drive below.
"""

# load data in
from google.colab import drive
drive.mount('/content/drive')## Dataset

# Define chess dataset
class ChessDataset(Dataset):
    def __init__(self, directory, transform=None):
        self.directory = directory
        self.transform = transform
        self.images = []
        self.labels = []

        for label, subdir in enumerate(['insufficient_material', 'sufficient_material']):
            subdir_path = os.path.join(directory, subdir)
            for filename in os.listdir(subdir_path):
                if filename.endswith('.png'):
                    self.images.append(os.path.join(subdir_path, filename))
                    self.labels.append(label)

    def __len__(self):
        return len(self.images)

    def __getitem__(self, idx):
        image_path = self.images[idx]
        image = Image.open(image_path).convert('RGB')
        label = self.labels[idx]

        if self.transform:
            image = self.transform(image)

        return image, label

data_transforms = {
    'train': transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ]),
    'val': transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ]),
}

"""## Part (a): Model and Training Setup"""

# load a pretrained ResNet model
model = models.resnet18(weights='ResNet18_Weights.DEFAULT')

# create the dataset
# Make sure the 'chess_dataset' folder is correctly uploaded to Google Colab or Google Drive and update the path if needed
if 'google.colab' in str(get_ipython()):
    folder = '/content/'
else:
    folder = ''

train_dataset = ChessDataset(folder + 'chess_dataset/train', transform=data_transforms['train'])
val_dataset = ChessDataset(folder + 'chess_dataset/val', transform=data_transforms['val'])


# define loss function and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr=0.001, momentum=0.9)

##########################
#  Beginning of Part a  ##
##########################

# TODO: modify the fully connected layer for binary classification
# hint: it might be helpful to print(model) to see how the model is structured
print(model)
model.fc = nn.Linear(model.fc.in_features, 2)
print(model)

# use a GPU if available
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
model = model.to(device)

# create the train_loader and val_loader
batch_size = 4
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)

"""## Part (b): Train and Validation"""

###########################
##  Beginning of Part b  ##
###########################

def train(epoch_num):
    # set the model to train mode
    model.train()

    running_loss = 0.0
    total_loss = 0.0
    running_count = 0
    total_count = 0

    for batch_index, (inputs, labels) in enumerate(train_loader):
        inputs = inputs.to(device)
        labels = labels.to(device)


        #TODO: complete the training loop. You will need to do the following:
        #1. zero the parameter gradients
        optimizer.zero_grad()
        #2. run a forward pass
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        #3. run a backwards pass and optimizer step
        loss.backward()
        optimizer.step()


        # update loss and count
        running_loss += loss.item() * inputs.size(0)
        total_loss += loss.item() * inputs.size(0)

        running_count += inputs.size(0)
        total_count += inputs.size(0)

        # print every 50 mini-batches
        if batch_index % 50 == 49:
            print('[%d, %5d] avg batch loss: %.3f avg epoch loss: %.3f' %
                (epoch_num + 1, batch_index + 1, running_loss / running_count, total_loss / total_count))
            running_loss = 0.0
            running_count = 0


def validate():
    # set the model to evaluation mode
    model.eval()
    total_loss = 0.0
    total_correct = 0
    total_count = 0

    # Validation loop
    with torch.no_grad():  # No need to track gradients for validation
        for inputs, labels in val_loader:
            inputs = inputs.to(device)
            labels = labels.to(device)


            #TODO:
            #run the forward pass (same as previous part)
            outputs = model(inputs)
            loss = criterion(outputs, labels)
            #from your output (which are probabilities for each class, find the predicted class)
            _, predicted = torch.max(outputs, 1) # predicted class = class with highest score
            correct_count = (predicted == labels).sum().item() # UPDATE

            # update loss and count
            total_loss += loss.item() * labels.size(0)
            total_correct += correct_count
            total_count += labels.size(0)

    accuracy = 100 * total_correct / total_count
    print()
    print(f"Evaluation loss: {total_loss / total_count :.3f}")
    print(f'Accuracy of the model on the validation images: {accuracy: .2f}%')
    print()

"""## Part (c)"""

###########################
##  Beginning of Part c  ##
###########################

# TODO: validate your model before training
print("Validation before training:")
validate()

num_epochs = 1
# TODO: train and validate your model
for epoch in range(num_epochs):
    print(f"Training epoch {epoch+1}")
    train(epoch)

    print("Validation after training:")
    validate()

