# -*- coding: utf-8 -*-
"""991594666_Code2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GFF1pIvZzmfXLECPoMpGYBTH5PnF28Mc
"""

# Imports
import numpy as np
import pandas as pd
import statsmodels.api as sm
from google.colab import files

uploaded = files.upload()
csvFileName = next(iter(uploaded))

def CalcBeta (csvFileName):
  pricesDF = pd.read_csv (csvFileName, index_col = 0)

  results = pricesDF.iloc[0,:]

  # clean invalid data : set to missing
  pricesDF[pricesDF <= 0] = np.nan
  returnsDF = pricesDF.pct_change(1, fill_method = None)

  # Regression
  x = sm.add_constant(returnsDF.iloc[:,0])
  for i in range (1, returnsDF.shape[1]):
    y = returnsDF.iloc[:,i]
    model = sm.OLS(y,x, missing = 'drop')
    results.iloc[i] = model.fit().params[1]

  # No beta for SPX
  results.iloc[0] = None

  return results

# Test 1
print('The Beta for 23026 is ' + str(CalcBeta(csvFileName).loc['23026']))

# Test 2
print('The Beta for 23579 is ' + str(CalcBeta(csvFileName).loc['23579']))

# Test 3
print('The Beta for 10145 is ' + str(CalcBeta(csvFileName).loc['10145']))

# Question 5
print('The Beta for 11674 is ' + str(CalcBeta(csvFileName).loc['11674']))

# Question 6
print('The Beta for 11308 is ' + str(CalcBeta(csvFileName).loc['11308']))