# -*- coding: utf-8 -*-
"""991594666_Code1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p_b2DRhqtgZJW22B2JKz6wW3pUEU9wYt
"""

# Imports
import numpy as np

# Function that simulates a path
def AssetPrice (T, sigma, mu, p , x_0) :
  x_current = x_0
  output = [x_current]

  for i in range (T) :
    z = np.random.binomial(1,p) * 2 - 1
    x_new = x_current * np.exp(mu + sigma * z)
    output.append(x_new)
    x_current = x_new

  return np.array(output)


# Function that estimates the probability that the opening value is the highest value
def CD_probability (number_simulations, T, sigma, mu, p, x_0, tolerance) :
  count_above = 0
  for i in range (number_simulations) :
    # Calculate series of firm values
    values = AssetPrice(T, sigma, mu, p, x_0)
    # Check if any of the values are below threshold
    if (sum(values > x_0 + tolerance) != 0) :
      count_above += 1
  return print('Probability that values goes below its initial valuation of ' + str(x_0) + ' is ' + str(1 - count_above/number_simulations))


# Test 1
T, mu, sigma, p, x_0 = 4, 0, 0.05, 0.5, 100
number_simulations = 100000
tolerance = 1e-7
print(CD_probability(number_simulations, T, sigma, mu, p, x_0, tolerance))


# Test 2
T, mu, sigma, p, x_0 = 8, 0, 0.05, 0.5, 100
number_simulations = 100000
tolerance = 1e-7
print(CD_probability(number_simulations, T, sigma, mu, p, x_0, tolerance))


# Question 2
T, mu, sigma, p, x_0 = 18, 0, 0.09, 0.5, 100
number_simulations = 100000
tolerance = 1e-7
print(CD_probability(number_simulations, T, sigma, mu, p, x_0, tolerance))


# Question 3
import matplotlib.pyplot as plt
T, mu, sigma, p, x_0 = 18, 0, 0.09, 0.5, 100
number_simulations = 5
plt.xlabel("Time Periods")
plt.ylabel("Firm Valuation")
plt.title("Paths of Possible Firm Valuations")

for i in range (number_simulations) :
  plt.plot(AssetPrice(T, sigma, mu, p, x_0))

plt.savefig("991594666_Figure1.pdf")