# -*- coding: utf-8 -*-
"""VENETCorentin-PS1-Q1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IYQzoQJpyVkYze1bL83dX7ZymlTIAVx_
"""

import random
import string

# Note: If you want to run this code to test your solution, you will need to install SciKit Learn and Numpy
# This can be done with: pip install scikit-learn numpy
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import log_loss

#######################
##  Helper Functions ##
#######################


def fit(X, y, phi, lmbd):
    '''
    Fits a logistic regression model on the data (X, y), using the parameters
    phi and lmbd. Returns the learned regression coefficients theta

    Parameters
    ----------
    X: np.array
        2-D feature matrix
    y: np.array
        1-D array of targets
    phi: np.array
        Feature maslmbd: float
        Regularization penalty weight

    Returns
    ----------
    theta: sklearn.LogisticRegression model
        Trained logistic regression model, with properties .coef_ and .intercept_
    '''
    if lmbd == 0: # no regularization
        theta = LogisticRegression(penalty=None)
    else:
        # C is inverse of lambda
        theta = LogisticRegression(penalty='l2', C=1/lmbd)

    # Assuming phi is feature mask
    theta.fit(X[:, phi], y)
    # cofficients of model can be access by theta.coef_ and theta.intercept_
    return theta


def predict(X, phi, theta):
    '''
    Returns predictions for given model theta on phi(X).

    Parameters
    ----------
    X: np.array
        2-D feature matrix
    phi: np.array
        Feature mask used to select subset of features
        e.g., if d=3, phi= [True, False, True] would select the first and last features
    theta: sklearn.LogisticRegression
        Trained logistic regression model, with properties .coef_ and .intercept_

    Returns
    ----------
    np.array
        1-D array of predictions of model theta on X for subset of features
        indicated by feature mask phi
    '''
    return theta.predict_proba(X[:, phi])


def logloss(y, y_hat):
    '''
    Returns logistic loss between targets y and predictions y_hat.

    Parameters
    ----------
    y: np.array
        1-D array of ground truth targets
    y_hat: np.array
        1-D array of predictions

    Returns
    ----------
    float
        Logistic loss between targets y and predictions y_hat
    '''
    return log_loss(y, y_hat)


####################
##  Example Data  ##
####################


# if you would like to test your code for problem 1.3, you can use this data
# and set of possible lambda/phis
np.random.seed(0)
N = 100
d = 5
X = np.random.normal(size=(N, d))
y = np.random.choice([0, 1], size=N)
lmbds = [0, 0.1, 1, 10]
phis = [np.random.choice(a=[True, False], size=d) for i in range(3)]
# make sure at least one feature from each feature mask is selected
for phi in phis:
    phi[0] = True

###################
##  Problem 1.1  ##
###################


def sweep_hyperparameters(X_train, y_train, X_val, y_val, lmbds, phis):
    '''
    Finds the best settings of lambda and phi, and trains a logistic regression model with these parameters.

    Parameters
    ----------
    X_train: np.array
        2-D matrix of training data features
    y_train: np.array
        1-D array of train targets
    X_val: np.array
        2-D matrix of validation data features
    y_val: np.array
        1-D array of validation targets
    lmbds: list
        List of possible settings of regularization term lambda to consider.
    phis: list
        List of feature masks to consider.
        Note: a feature mask is a boolean array (e.g., [True, False, True]) that
        specifies what features to use vs ignore.

    Returns
    ----------
    best_lmbd: float
        chosen regularization parameter lambda
    best_phi: np.array
        chosen feature mask (i.e., feature subset) phi
    best_theta: sklearn.LogisticRegression model
        Logistic regresion model trained using best_lmbd and best_phi
    '''
    losses = []
    # fixing a (lmbd, phi) subset
    for lmbd in lmbds:
        for phi in phis:
            # your code goes here
            theta = fit(X_train, y_train, phi, lmbd)
            y_hat = predict(X_val,phi,theta)
            loss_here = logloss(y_val,y_hat)
            losses.append([loss_here,lmbd,phi,theta])

    loss, best_lmbd, best_phi, best_theta = min(losses, key = lambda x:x[0])
    return best_lmbd, best_phi, best_theta

print(sweep_hyperparameters(X, y, X, y, lmbds, phis))

###################
##  Problem 1.2  ##
###################


def evaluate_model(theta, phi, X_test, y_test):
    '''
    Evaluates a trained logistic regression model.

    Parameters
    ----------
    theta: sklearn.LogisticRegression
        rained logistic regression model
    phi: np.array
        Feature mask used to select subset of features
    X_test: np.array
        2-D matrix of test data features
    y_test: np.array
        1-D array of test targets

    Returns
    ----------
    loss: float
        loss of trained model on some partition of the data (you need to decide what partition)
    '''
    # TODO: your code goes here
    y_hat = predict(X_test,phi,theta)
    loss = logloss(y_test,y_hat)
    return loss

###################
##  Problem 1.3  ##
###################


def train_and_eval_model(X, y, lmbds, phis):
    '''
    Uses a feature matrix X and labels y to train and evaluate
    a logistic regression model.

    Sweeps over all combinations of lambda and phi to choose the
    best setting.

    Parameters
    ----------
    X: np.array
        2-D feature matrix
    y: np.array
        1-D array of targets
    lmbds: list
        List of possible settings of regularization term lambda to consider.
    phis: list
        List of feature masks to consider.
        Note: a feature mask is a boolean array (e.g., [True, False, True]) that
        specifies what features to use vs ignore.
    '''
    # 1. Split data into groups, assumes the data is randomly shuffled beforehand
    n_samples = len(X)
    n_train = int(n_samples * 0.5)
    n_val = int(n_samples * 0.25)
    X_train, y_train = X[:n_train], y[:n_train]
    X_val, y_val = X[n_train:n_train+n_val], y[n_train:n_train+n_val]
    X_test, y_test = X[n_train+n_val:], y[n_train+n_val:]

    # 2. Choose best hyperparameters and train model w/ these parameters
    # TODO: your code goes here
    best_lmbd, best_phi, best_theta = sweep_hyperparameters(X_train, y_train, X_val, y_val, lmbds, phis)

    # 3. Produce estimate of how model will perform on unseen data
    # TODO: your code goes here
    loss = evaluate_model(best_theta, best_phi, X_test, y_test) # replace this line with your code
    print("Test Loss", loss)

train_and_eval_model(X, y, lmbds, phis)

"""QUESTION 4

Expected better model: M1.

The model that is going to perform better is the model M1. In fact, both models achieve the same validation error, but M1 uses only 3 features while M2 uses 5 features. That means that M1 reaches the same performance with a simpler representation of the data.

Indeed, when two models have the same validation performance, the model with fewer features is usually preferable because it tends to have lower variance and is less subject to overfitting. So on an unseen test dataset, M1 should generalize better (or at least be more robust), since it is less likely to be fitting noise in the training set.

QUESTION 5a

Expected better model for a new country: the one optimized on the country-based split.

The model trained with the country-based split is the one I would expect to perform better when deploying it in a new country. In fact, the country-based split forces the model to generalize across countries, because it is evaluated on countries that were not used during training.

On the contrary, with a random split, we often have data from the same countries in both train and test sets. This makes the test performance less representative of what will happen in a new country, because the model can rely on country-specific patterns that won’t transfer. So even if both approaches give similar train/test error, the country-based split is more aligned with the real deployment setting (“new country”), and therefore it should generalize better.

QUESTION 5b

Better split: time-based split (train on past, test on future), because the axis of generalization is time.

Here we have an issue with the fact that user preferences shift over time, so the random split is not realistic. We should instead split the data using a time-based split, meaning we train on older data and test on more recent data (for example: train on the first part of the timeline, validate on the next part, and test on the last part).

This is exactly the idea of an axis of generalization: we want the train/test split to reflect the axis along which the data will change in production. Here the axis is time, not “random examples”. If we split randomly, we implicitly assume the distribution is the same across time, which is false in this setting, and that explains why performance drops in production.

Also, in practice, we can use a rolling or forward validation approach, and regularly retrain the model as new data arrives, because the goal is to keep the model adapted to the most recent user behaviors.
"""