# -*- coding: utf-8 -*-
"""PS6_VENETCorentin.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nRCZBr4SKDxO_AgDUN4tOBexmspQ2n3s
"""

import numpy as np
import matplotlib.pyplot as plt

# Parameters
mu = 0.05
sigma = 0.15
T = 1.0
phi = 0.5

# Wealth functions
def WT_single_from_ST(ST_over_S0, sigma, T, phi):
    return (ST_over_S0)**phi * np.exp(0.5 * sigma**2 * T * (phi - phi**2))

def WT_split_from_ST(ST_over_S0, sigma, T, phi):
    term_pos = 0.5 * WT_single_from_ST(ST_over_S0, sigma, T, +phi)
    term_neg = 0.5 * WT_single_from_ST(ST_over_S0, sigma, T, -phi)
    return term_pos + term_neg

# Compute values
ST_over_S0 = np.linspace(0.4, 2.5, 400)
WT_split_over_W0  = WT_split_from_ST(ST_over_S0, sigma, T, phi)

# Plot: split (+phi, -phi) strategy
plt.figure(figsize=(7,5))
plt.plot(ST_over_S0, WT_split_over_W0, color='darkorange', lw=2)
plt.xlabel("Normalized stock price  $S_T / S_0$")
plt.ylabel("Normalized terminal wealth  $W_T / W_0$")
plt.title("Split strategy: +$\\phi$ and -$\\phi$ (each 1/2 of $W_0$)\n"
          "$\\mu={:.2f}$, $\\sigma={:.2f}$, $T={:.1f}$, $\\phi={:.2f}$"
          .format(mu, sigma, T, phi))
plt.grid(True)
plt.show()

import numpy as np
from math import exp
from math import comb

# Inputs
sigma = 0.2
mu = 0.1
dt = 1/52
N = 104
r = 0.04/52
S0 = 1.0
W0 = 1.0
floor = 0.9

# Parameters of binomial tree
u = exp(sigma*np.sqrt(dt))
d = 1.0/u
p = (exp(mu*dt) - d) / (u - d)
q = ((1+r) - d) / (u - d)
beta = 1/(1+r)

# SPD and Arrow prices at terminal nodes n=0..N
def pi_T(n):
    return (beta**N) * (q/p)**n * ((1-q)/(1-p))**(N-n)

def arrow(n):
    return (beta**N) * comb(N, n) * (q**n) * ((1-q)**(N-n))

# Terminal payoff for given lambda
def payoff_vec(lmbda):
    pis = np.array([pi_T(n) for n in range(N+1)])
    uncon = 1.0 / (lmbda * pis)
    return np.maximum(floor, uncon)

# Time-0 price for given lambda
def V0_of_lambda(lmbda):
    W = payoff_vec(lmbda)
    a = np.array([arrow(n) for n in range(N+1)])
    return float(np.dot(a, W))

# Solve lambda by binary search
lo, hi = 1e-8, 1e8
for _ in range(100):
    mid = (lo+hi)/2
    if V0_of_lambda(mid) > W0:
        lo = mid
    else:
        hi = mid
lam = (lo+hi)/2

# Backward induction
V = Wterm.astype(float).copy()
for _ in range(N-1):
    k = len(V)
    V = beta * ( q*V[1:k] + (1-q)*V[0:k-1] )

V_d, V_u = V[0], V[1]
theta0 = (V_u - V_d) / ((u - d) * S0)

print(f"lambda ≈ {lam:.6e}")
print(f"V0 (check) ≈ {V0_of_lambda(lam):.6f}")
print(f"Delta (shares) at t=0: theta0 ≈ {theta0:.6f}")