# -*- coding: utf-8 -*-
"""ps8_venetcorentin_code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EK2Y5Yz_9XpoOSdkM9piOOCqTD68manZ
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm
from numpy import save, load
import time

# Parameters
T = 24
S_BAR = 1.0
rho = 0.99
sigma = 0.01
lam = 0.01
X0 = 1.0


# Grids
# State 1: price deviation x_t = S_t - S_BAR
dx = sigma / 3.0
sigmass = np.sqrt(sigma**2 / (1 - rho**2))
xmax = 5 * sigmass
Nx = int(2 * np.ceil(xmax / dx) + 1)
xgrid = np.linspace(-xmax, xmax, Nx)
dx = xgrid[1] - xgrid[0]

# State 2: inventory W_t (shares left to sell)
Wmax = X0
NW = 81
Wgrid = np.linspace(0.0, Wmax, NW)
dW = Wgrid[1] - Wgrid[0]

# Control: number of shares to sell x_t
Ntheta = 81
thetagrid = np.linspace(0.0, Wmax, Ntheta)
dtheta = thetagrid[1] - thetagrid[0]


# Transition matrix for x_t
TrM_x = np.full((Nx, Nx), 0.0)

for i in range(Nx):
    mean = rho * xgrid[i]
    p = np.zeros(Nx)
    # interior points
    p[1:-1] = norm(mean, sigma).pdf(xgrid[1:-1]) * dx
    # first bin (left tail)
    p[0] = norm(mean, sigma).cdf(xgrid[0] + 0.5 * dx)
    # last bin (right tail)
    p[-1] = 1.0 - norm(mean, sigma).cdf(xgrid[-1] - 0.5 * dx)
    p = p / np.sum(p)
    TrM_x[i, :] = p


# Dynamic Programming
# J[t, ix, iw] = value function
# theta_opt[t, ix, iw] = optimal shares to sell at t

def build_dp():
    cur = time.time()

    J = np.full((T+1, Nx, NW), 0.0)
    theta_opt = np.full((T, Nx, NW), 0.0)

    # Terminal condition: at time T, value is zero (no more trading possible).
    # Constraint "W_T = 0" is enforced by forcing liquidation at t = T-1.

    # Backward induction
    for t in range(T-1, -1, -1):
        print(f"DP step t = {t}")
        for ix in range(Nx):
            x_prev = xgrid[ix]
            # Conditional expected execution price at time t:
            # E[S_t | x_{t-1}] = S_BAR + rho * x_prev
            m_t = S_BAR + rho * x_prev
            # probabilities of x_t given x_{t-1}=x_prev
            p_next = TrM_x[ix, :]

            for iw in range(NW):
                W = Wgrid[iw]

                # If no inventory, nothing to do
                if W <= 1e-12:
                    J[t, ix, iw] = 0.0
                    theta_opt[t, ix, iw] = 0.0
                    continue

                # Allowed controls: 0 <= theta <= W
                valid = thetagrid <= W
                theta_candidates = thetagrid[valid]
                if theta_candidates.size == 0:
                    J[t, ix, iw] = 0.0
                    theta_opt[t, ix, iw] = 0.0
                    continue

                # At final trading period t = T-1 we must liquidate everything:
                if t == T-1:
                    theta_candidates = np.array([W])

                values = []
                for theta in theta_candidates:
                    immediate = theta * (m_t - lam * theta)
                    W_next = W - theta
                    # snap to nearest inventory grid point
                    jW_next = int(np.argmin(np.abs(Wgrid - W_next)))

                    J_next_vec = J[t+1, :, jW_next]
                    EV = p_next.dot(J_next_vec)

                    values.append(immediate + EV)

                values = np.array(values)
                best_idx = int(np.argmax(values))
                J[t, ix, iw] = values[best_idx]
                theta_opt[t, ix, iw] = theta_candidates[best_idx]

    save("valueFunction.npy", J)
    save("optimalTheta.npy", theta_opt)

    now = time.time()
    print("DP finished in minutes:", (now - cur) / 60.0)


# Interpolation helper
def get_optimal_theta(theta_opt, t, S_prev, W):
    x_prev = S_prev - S_BAR
    ix = int(np.argmin(np.abs(xgrid - x_prev)))
    iw = int(np.argmin(np.abs(Wgrid - W)))
    return theta_opt[t, ix, iw]


## QUESTION A analytical solution + plot

def analytic_two_period_x(W, S_prev):
    slope = rho * (1.0 - rho) / (4.0 * lam)
    x_star = W / 2.0 + slope * (S_prev - S_BAR)
    # clamp to [0, W]
    return np.clip(x_star, 0.0, W)

def plot_part_a(theta_opt):
    t_eval = T - 2
    W_eval = 1.0

    S_vals = np.linspace(S_BAR - 3*sigma, S_BAR + 3*sigma, 101)
    x_num = np.array([get_optimal_theta(theta_opt, t_eval, S, W_eval) for S in S_vals])
    x_ana = np.array([analytic_two_period_x(W_eval, S) for S in S_vals])

    plt.figure()
    plt.plot(S_vals, x_num, label="Numerical DP policy (t = T-2)")
    plt.plot(S_vals, x_ana, "--", label="Analytical 2-period solution")
    plt.xlabel(r"$S_{t-1}$")
    plt.ylabel(r"$x_t$")
    plt.title("Part (a): Optimal trade at t = T-2")
    plt.legend()
    plt.grid(True)
    plt.show()


## QUESTION B plot

def plot_part_b(theta_opt):
    t_eval = T // 2
    W_eval = 0.5
    S_vals = np.linspace(S_BAR - 3*sigma, S_BAR + 3*sigma, 101)
    x_vals = np.array([get_optimal_theta(theta_opt, t_eval, S, W_eval) for S in S_vals])

    plt.figure()
    plt.plot(S_vals, x_vals)
    plt.xlabel(r"$S_{t-1}$")
    plt.ylabel(r"$x_t$")
    plt.title(f"Part (b): Optimal policy at t = {t_eval}, W_t = 0.5")
    plt.grid(True)
    plt.show()


## QUESTION C plot

def plot_part_c(theta_opt):
    t_eval = T // 2
    S_eval = 1.0
    W_vals = np.linspace(0.0, X0, 101)
    x_vals = np.array([get_optimal_theta(theta_opt, t_eval, S_eval, W) for W in W_vals])

    plt.figure()
    plt.plot(W_vals, x_vals)
    plt.xlabel(r"$W_t$")
    plt.ylabel(r"$x_t$")
    plt.title(f"Part (c): Optimal policy at t = {t_eval}, S_{{t-1}} = 1")
    plt.grid(True)
    plt.show()


## QUESTION D simulation

def simulate_once(theta_opt, rho_sim, N_paths=10000, seed=0):
    """
    Compare DP-optimal strategy vs uniform strategy (sell 1/T each period),
    for a given rho_sim.
    """
    rng = np.random.default_rng(seed)

    profits_opt = np.zeros(N_paths)
    profits_uni = np.zeros(N_paths)

    x_uniform = X0 / T

    for n in range(N_paths):
        S_prev_opt = 1.0
        S_prev_uni = 1.0
        W_opt = X0
        W_uni = X0

        pi_opt = 0.0
        pi_uni = 0.0

        for t in range(T):
            # Optimal strategy
            x_t_opt = get_optimal_theta(theta_opt, t, S_prev_opt, W_opt)
            eps = rng.normal(0.0, sigma)
            S_t_opt = S_BAR + rho_sim * (S_prev_opt - S_BAR) + eps
            exec_price_opt = S_t_opt - lam * x_t_opt
            pi_opt += x_t_opt * exec_price_opt
            W_opt -= x_t_opt
            if W_opt < 0:
                W_opt = 0.0
            S_prev_opt = S_t_opt

            # Uniform strategy
            x_t_uni = min(x_uniform, W_uni)
            eps2 = rng.normal(0.0, sigma)
            S_t_uni = S_BAR + rho_sim * (S_prev_uni - S_BAR) + eps2
            exec_price_uni = S_t_uni - lam * x_t_uni
            pi_uni += x_t_uni * exec_price_uni
            W_uni -= x_t_uni
            if W_uni < 0:
                W_uni = 0.0
            S_prev_uni = S_t_uni

        profits_opt[n] = pi_opt
        profits_uni[n] = pi_uni

    return profits_opt.mean(), profits_uni.mean()


def experiment_part_d(theta_opt):
    rhos = [0.0, 0.3, 0.6, 0.9, 0.99]
    N_paths = 10000

    print("\nPart (d): Simulation comparison (DP vs uniform)")
    print("rho\tE[Pi_opt]\tE[Pi_uniform]\tDifference")
    for r in rhos:
        mean_opt, mean_uni = simulate_once(theta_opt, rho_sim=r, N_paths=N_paths, seed=123)
        diff = mean_opt - mean_uni
        print(f"{r:.2f}\t{mean_opt:.6f}\t{mean_uni:.6f}\t{diff:.6f}")



if __name__ == "__main__":
    # First run: build DP and save value function & policy
    build_dp()

    # Load them back
    J = load("valueFunction.npy")
    theta_opt = load("optimalTheta.npy")

    # Plots
    plot_part_a(theta_opt)
    plot_part_b(theta_opt)
    plot_part_c(theta_opt)

    # Simulation experiment for (d)
    experiment_part_d(theta_opt)

import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt


# Parameters
Delta = 1.0 / 252.0
rF = 0.05
mu_S = 0.10
eta_x = -0.2
theta = 4.0
gamma_x = 2.0
rho = -0.9
x_bar = np.log(0.1)

S0 = 1.0
x0 = x_bar

T_days = 126
Nsteps = T_days

K = 0.0001


# Path simulation (under Q)
def simulate_paths(Npaths, seed=None):
    rng = np.random.default_rng(seed)
    dt = Delta

    S = np.full((Npaths, Nsteps + 1), S0, dtype=float)
    x = np.full((Npaths, Nsteps + 1), x0, dtype=float)
    r = np.zeros((Npaths, Nsteps + 1), dtype=float)

    sqrt_dt = np.sqrt(dt)
    sqrt_one_minus_rho2 = np.sqrt(1.0 - rho**2)

    for n in range(Nsteps):
        eps_S = rng.normal(size=Npaths)
        eps_v = rng.normal(size=Npaths)

        v_t = np.exp(x[:, n])

        # Price of stock risk at time t
        eta_S_t = ((mu_S - rF) / np.sqrt(v_t)
                   + gamma_x * sqrt_dt * (rho * eps_S + sqrt_one_minus_rho2 * eps_v))

        # Update x
        x[:, n+1] = (x[:, n]
                     - theta * (x[:, n] - x_bar) * dt
                     - (rho * eta_S_t + sqrt_one_minus_rho2 * eta_x) * gamma_x * sqrt_dt
                     + gamma_x * sqrt_dt * (rho * eps_S + sqrt_one_minus_rho2 * eps_v))

        # Update S
        S[:, n+1] = S[:, n] * np.exp((rF - 0.5 * v_t) * dt + np.sqrt(v_t * dt) * eps_S)
        r[:, n+1] = np.log(S[:, n+1] / S[:, n])

    # 10-day moving average of squared log-returns
    RV = np.zeros_like(S)
    window = 10
    for t in range(window, Nsteps + 1):
        sq = r[:, t-window+1:t+1]**2
        RV[:, t] = sq.mean(axis=1)

    return S, x, RV


def compute_payoff(RV):
    return np.maximum(RV - K, 0.0)


# LSMC training
def lsmc_train(Npaths_train=100000, seed=123):
    S, x, RV = simulate_paths(Npaths_train, seed=seed)
    dt = Delta
    disc = np.exp(-rF * dt)

    Npaths, T1 = RV.shape
    Payoff = compute_payoff(RV)

    # CF[i, n] = optimal (discounted) value from time n for path i
    CF = np.zeros_like(Payoff)
    CF[:, -1] = Payoff[:, -1]

    # regression coefficients for basis 1, x, RV, x^2, x*RV, RV^2
    beta = np.zeros((T1, 6))

    # exercise only when 10-day RV is defined
    start = 10

    for n in range(T1 - 2, start - 1, -1):
        itm = Payoff[:, n] > 0

        if not np.any(itm):
            CF[:, n] = disc * CF[:, n+1]
            continue

        X_state = x[itm, n]
        RV_state = RV[itm, n]

        # basis functions: 1, x, RV, x^2, x*RV, RV^2
        Xmat = np.column_stack([
            np.ones_like(X_state),
            X_state,
            RV_state,
            X_state**2,
            X_state * RV_state,
            RV_state**2
        ])

        # Y = discounted future cash-flow
        Y = disc * CF[itm, n+1]

        reg = LinearRegression(fit_intercept=False)
        reg.fit(Xmat, Y)
        beta[n, :] = reg.coef_

        C = reg.predict(Xmat)
        payoff_n = Payoff[itm, n]

        exercise_itm = payoff_n > C
        itm_indices = np.where(itm)[0]
        ex_paths = itm_indices[exercise_itm]

        no_ex = np.setdiff1d(np.arange(Npaths), ex_paths)

        CF[ex_paths, n] = payoff_n[exercise_itm]
        CF[no_ex, n] = disc * CF[no_ex, n+1]

    # for times before RV is defined, everyone holds
    for n in range(start - 1, -1, -1):
        CF[:, n] = disc * CF[:, n+1]

    price0 = CF[:, 0].mean()
    return beta, price0, (S, x, RV, CF)



# Exercise boundary
def exercise_boundary(beta, t_index, x_samples=None):
    b = beta[t_index, :]
    if x_samples is None:
        x_samples = np.linspace(x_bar - 1.0, x_bar + 1.0, 50)

    x_vals = []
    rv_vals = []

    b0, b1, b2, b3, b4, b5 = b

    for x_val in x_samples:
        A = b5
        B = b2 + b4 * x_val - 1.0
        C = b0 + b1 * x_val + b3 * x_val**2 + K

        disc = B*B - 4*A*C
        if disc < 0:
            continue

        sqrt_disc = np.sqrt(disc)

        if abs(A) < 1e-12:
            if abs(B) < 1e-12:
                continue
            rv = -C / B
            if rv > K and np.isfinite(rv):
                x_vals.append(x_val)
                rv_vals.append(rv)
            continue

        rv1 = (-B + sqrt_disc) / (2*A)
        rv2 = (-B - sqrt_disc) / (2*A)
        candidates = [rv for rv in (rv1, rv2) if rv > K and np.isfinite(rv)]
        if not candidates:
            continue

        rv_star = min(candidates)
        x_vals.append(x_val)
        rv_vals.append(rv_star)

    return np.array(x_vals), np.array(rv_vals)


# QUESTION A plot

def plot_exercise_boundary(beta, x_paths, RV_paths, t_index, sample_paths=5000):
    """
    (a) Plot the exercise boundary at t_index, with and without state realizations.
    """
    x_bd, rv_bd = exercise_boundary(beta, t_index)

    # boundary only
    plt.figure(figsize=(7, 5))
    plt.plot(x_bd, rv_bd, 'r-', lw=2)
    plt.xlabel(r'$x_t$')
    plt.ylabel(r'$\mathrm{RV}_t$')
    plt.title(f'Exercise boundary at t = {t_index}')
    plt.grid(True)
    plt.show()

    # boundary + simulated states
    plt.figure(figsize=(7, 5))
    Npaths = x_paths.shape[0]
    idx = np.random.choice(Npaths, size=min(sample_paths, Npaths), replace=False)
    plt.scatter(x_paths[idx, t_index], RV_paths[idx, t_index],
                s=5, alpha=0.3, label='Simulated states')
    plt.plot(x_bd, rv_bd, 'r-', lw=2, label='Exercise boundary')
    plt.xlabel(r'$x_t$')
    plt.ylabel(r'$\mathrm{RV}_t$')
    plt.title(f'Exercise boundary at t = {t_index} with state realizations')
    plt.legend()
    plt.grid(True)
    plt.show()



# QUESTION B Valuation

def lsmc_value_with_policy(beta, Npaths_eval=10000, seed=999):
    S, x, RV = simulate_paths(Npaths_eval, seed=seed)
    Payoff = compute_payoff(RV)

    dt = Delta
    disc = np.exp(-rF * dt)

    Npaths, T1 = RV.shape
    CF = np.zeros_like(Payoff)
    CF[:, -1] = Payoff[:, -1]

    start = 10

    for n in range(T1 - 2, start - 1, -1):
        b = beta[n, :]
        Xn = x[:, n]
        RVn = RV[:, n]

        Xmat_all = np.column_stack([
            np.ones_like(Xn),
            Xn,
            RVn,
            Xn**2,
            Xn * RVn,
            RVn**2
        ])
        C_all = Xmat_all @ b

        payoff_n = Payoff[:, n]
        itm = payoff_n > 0

        ex = np.where(itm & (payoff_n > C_all))[0]
        no_ex = np.setdiff1d(np.arange(Npaths), ex)

        CF[ex, n] = payoff_n[ex]
        CF[no_ex, n] = disc * CF[no_ex, n+1]

    for n in range(start - 1, -1, -1):
        CF[:, n] = disc * CF[:, n+1]

    price0 = CF[:, 0].mean()
    std0 = CF[:, 0].std(ddof=1)
    ci_half = 1.96 * std0 / np.sqrt(Npaths_eval)
    return price0, (price0 - ci_half, price0 + ci_half), (S, x, RV)



if __name__ == "__main__":
    # LSMC training
    beta, train_price0, (S_train, x_train, RV_train, CF_train) = lsmc_train(
        Npaths_train=100000, seed=0
    )
    print("Training estimate V0 :", train_price0)

    # (a) Exercise boundary 60 days before maturity
    t_star = Nsteps - 60
    plot_exercise_boundary(beta, x_train, RV_train, t_star, sample_paths=5000)

    # (b) Out-of-sample valuation with learned policy
    price_est, ci, (S_eval, x_eval, RV_eval) = lsmc_value_with_policy(
        beta, Npaths_eval=10000, seed=1
    )
    print("Estimated option value at t=0:", price_est)
    print("95% confidence interval:", ci)