# -*- coding: utf-8 -*-
"""PS5_Q5_VENETCorentin.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rG5Wkwckc3VFLZCjtNii0Peg_aP-krNT
"""

import math
import numpy as np
import pandas as pd
from scipy.stats import norm
import matplotlib.pyplot as plt


# QUESTION (a)

def MCprice(S0, K, rf, T, sigma, Nt, Np, contract="call"):
    dt = T / Nt
    Z = np.random.choice([-1.0, 1.0], size=(Nt, Np))
    ret = (rf - 0.5 * sigma**2) * dt + sigma * math.sqrt(dt) * Z
    logX = np.cumsum(ret, axis=0)
    ST = S0 * np.exp(logX[-1, :])

    if contract == "call":
        payoff = np.maximum(ST - K, 0.0)
    elif contract == "put":
        payoff = np.maximum(K - ST, 0.0)
    elif contract == "straddle":
        payoff = np.maximum(ST - K, 0.0) + np.maximum(K - ST, 0.0)
    elif contract == "binary_call":
        payoff = (ST > K).astype(float)
    elif contract == "binary_put":
        payoff = (ST < K).astype(float)

    disc = math.exp(-rf * T)
    price = disc * payoff.mean()
    se = disc * payoff.std(ddof=1) / math.sqrt(Np)

    return {"price": float(price), "se": float(se)}


def analytical_values(S0, K, rf, T, sigma):
    d1 = (math.log(S0 / K) + (rf + 0.5 * sigma**2) * T) / (sigma * math.sqrt(T))
    d2 = d1 - sigma * math.sqrt(T)

    call = S0 * norm.cdf(d1) - K * math.exp(-rf * T) * norm.cdf(d2)
    put = K * math.exp(-rf * T) * norm.cdf(-d2) - S0 * norm.cdf(-d1)
    straddle = call + put
    bin_call = math.exp(-rf * T) * norm.cdf(d2)
    bin_put = math.exp(-rf * T) * norm.cdf(-d2)

    return {"call": float(call), "put": float(put), "straddle": float(straddle), "binary_call": float(bin_call), "binary_put": float(bin_put)}


def comparation(S0, K, rf, T, sigma, Nt, Np):
    contracts = ["call", "put", "straddle", "binary_call", "binary_put"]
    analytic = analytical_values(S0, K, rf, T, sigma)
    rows = []

    for c in contracts:
        mc = MCprice(S0, K, rf, T, sigma, Nt, Np, contract=c)
        ana = analytic[c]
        abs_err = mc["price"] - ana
        rows.append({"Contract": c, "MC Price": mc["price"], "MC SE": mc["se"], "95% CI Lower": mc["price"] - 1.96 * mc["se"], "95% CI Upper": mc["price"] + 1.96 * mc["se"], "BS Analytic": ana, "Abs Error": abs_err,})

    return pd.DataFrame(rows)

S0, K, rf, T, sigma, Nt, Np = 100.0, 120.0, 0.05, 2.0 / 3.0, 0.30, 1000, 100000
table_Qa = comparation(S0, K, rf, T, sigma, Nt, Np)
print(table_Qa.to_string(index=False))



# Question (b)

def convergence_call_vs_Np(S0, K, rf, T, sigma, Nt, Np_list):
    rows = []
    for npi in Np_list:
        mc = MCprice(S0, K, rf, T, sigma, Nt, npi, contract="call")
        rows.append({"Np": int(npi), "MC Price": mc["price"], "MC SE": mc["se"]})
    return pd.DataFrame(rows)


def plot_convergence(conv_df, bs_call):
    plt.figure()
    plt.semilogx(conv_df["Np"], conv_df["MC Price"], marker="o")
    plt.axhline(bs_call, linestyle="--")
    plt.xlabel("Number of paths (Np)")
    plt.ylabel("Call price")
    plt.title("Monte Carlo call price vs Np (semi-log x)")
    plt.tight_layout()
    plt.show()

    plt.figure()
    plt.semilogx(conv_df["Np"], conv_df["MC SE"], marker="o")
    plt.xlabel("Number of paths (Np)")
    plt.ylabel("Standard error")
    plt.title("Standard error vs Np (semi-log x)")
    plt.tight_layout()
    plt.show()


Np_list = [500, 1000, 2000, 4000, 8000, 16000, 32000, 64000, 128000, 256000]
conv_df = convergence_call_vs_Np(S0, K, rf, T, sigma, Nt, Np_list)
bs_call = analytical_values(S0, K, rf, T, sigma)["call"]
plot_convergence(conv_df, bs_call)