# -*- coding: utf-8 -*-
"""PS4_Q6_VENETCorentin.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aWcLXufU5OIbQDhXdeE9Psr1vsf54LOG
"""

def BTvalues (S, K, T, Ru, Rd, Rf) :
  step = T
  phi_u = ((Rf - Rd)/(Ru - Rd))/Rf
  phi_d = ((Ru - Rf)/(Ru - Rd))/Rf
  payoffs_call = [max(0,S*Ru**(T-k)*Rd**k - K) for k in range (T+1)]
  payoffs_put = [max(0,K - S*Ru**(T-k)*Rd**k) for k in range (T+1)]
  while step > 0 :
    price_call = [0 for _ in range (step)]
    price_put = [0 for _ in range (step)]
    for i in range (step) :
      intrinsic_call = max(0,S*Ru**(step-1-i)*Rd**i - K)
      intrinsic_put = max(0,K - S*Ru**(step-1-i)*Rd**i)
      price_call[i] = max(phi_u*payoffs_call[i] + phi_d*payoffs_call[i+1], intrinsic_call)
      price_put[i] = max(phi_u*payoffs_put[i] + phi_d*payoffs_put[i+1], intrinsic_put)
    delta_call = [(payoffs_call[k] - payoffs_call[k+1])/(S*Ru**(step-k)*Rd**(k)-S*Ru**(step-k-1)*Rd**(k+1)) for k in range (step)]
    delta_put = [(payoffs_put[k] - payoffs_put[k+1])/(S*Ru**(step-k)*Rd**(k)-S*Ru**(step-k-1)*Rd**(k+1)) for k in range (step)]
    B_call = [price_call[k] - delta_call[k]*S*Ru**(step-k-1)*Rd**(k) for k in range (step)]
    B_put = [price_put[k] - delta_put[k]*S*Ru**(step-k-1)*Rd**(k) for k in range (step)]
    payoffs_call = price_call
    payoffs_put = price_put
    step -= 1
  return (price_call[0], delta_call[0], B_call[0]),(price_put[0], delta_put[0], B_put[0])

BTvalues(16,16,6,2,1/2,1.25)