# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-b-97bRHyshfp-NQOaKVyIvc3cMB_JFx
"""

## QUESTION A

import numpy as np
import pandas as pd

df = pd.read_csv("Data_Pred_Return.csv")

if 'Unnamed: 0' in df.columns:
    df = df.drop(columns=['Unnamed: 0'])

df['dates'] = pd.to_datetime(df['dates'])
df = df.sort_values(['cusip', 'dates']).reset_index(drop=True)

# Log transforms of level variables
df['log_MV']    = np.where(df['MV']    > 0, np.log(df['MV']),    np.nan)
df['log_Price'] = np.where(df['Price'] > 0, np.log(df['Price']), np.nan)
df['log_Sales'] = np.where(df['Sales'] > 0, np.log(df['Sales']), np.nan)

# Cross-sectional demeaning
for col in ['log_MV', 'log_Price', 'log_Sales']: df[col + '_cs'] = df.groupby('dates')[col].transform(lambda x: x - x.mean())

# Sales growth
df['Sales_growth'] = df.groupby('cusip')['log_Sales'].diff()

# Ratios
df['leverage'] = df['SD2A'] + df['LD2A']
df['log_M2B'] = np.where(df['M2B'] > 0, np.log(df['M2B']), np.nan)
pe_low, pe_high = df['PE'].quantile([0.01, 0.99]) #cap extreme PE values to reduce outliers
df['PE_winsor'] = df['PE'].clip(lower=pe_low, upper=pe_high)

# Momentum
g = df.groupby('cusip', group_keys=False)
df['ret_1m']  = g['RET'].shift(1)
df['ret_3m']  = g['RET'].shift(1).rolling(3).sum()
df['ret_6m']  = g['RET'].shift(1).rolling(6).sum()
df['ret_12m'] = g['RET'].shift(1).rolling(12).sum()

# Final feature set
feature_cols = [
    'log_MV_cs',
    'log_Price_cs',
    'log_Sales_cs',
    'Sales_growth',
    'M2B',
    'log_M2B',
    'PE_winsor',
    'S2A',
    'SD2A',
    'LD2A',
    'leverage',
    'ret_1m',
    'ret_3m',
    'ret_6m',
    'ret_12m'
]

print(df[feature_cols].head())


## QUESTION B

df = df.sort_values(['cusip', 'dates']).reset_index(drop=True)
df['RET_lead'] = df.groupby('cusip')['RET'].shift(-1)
df['y'] = (df['RET_lead'] > 0).astype(int)
df = df.dropna(subset=['RET_lead'])

features = feature_cols

X = df[features].copy()
y = df['y'].copy()

valid = X.notnull().all(axis=1)
X = X[valid]
y = y[valid]
df_clean = df[valid]

train_end = pd.to_datetime("2011-12-31")

train_mask = df_clean['dates'] <= train_end
test_mask  = df_clean['dates'] > train_end

X_train = X[train_mask]
X_test  = X[test_mask]
y_train = y[train_mask]
y_test  = y[test_mask]

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

logit_model = Pipeline([('scaler', StandardScaler()),('logit', LogisticRegression(solver='lbfgs',max_iter=2000))])
logit_model.fit(X_train, y_train)


## QUESTION C

from sklearn.model_selection import TimeSeriesSplit, GridSearchCV

tscv = TimeSeriesSplit(n_splits=5)
C_grid = np.logspace(-3, 3, 13)

ridge_pipe = Pipeline([('scaler', StandardScaler()),('logit', LogisticRegression(penalty='l2',solver='lbfgs',max_iter=5000))])
ridge_cv = GridSearchCV(ridge_pipe,param_grid={'logit__C': C_grid},cv=tscv,scoring='neg_log_loss',n_jobs=-1)
ridge_cv.fit(X_train, y_train)
ridge_best = ridge_cv.best_estimator_
best_C_ridge = ridge_cv.best_params_['logit__C']
best_lambda_ridge = 1 / best_C_ridge
print("Best C for Ridge:", best_C_ridge)
print("Best lambda for Ridge:", best_lambda_ridge)

lasso_pipe = Pipeline([('scaler', StandardScaler()),('logit', LogisticRegression(penalty='l1',solver='liblinear',max_iter=5000))])
lasso_cv = GridSearchCV(lasso_pipe,param_grid={'logit__C': C_grid},cv=tscv,scoring='neg_log_loss',n_jobs=-1)
lasso_cv.fit(X_train, y_train)
lasso_best = lasso_cv.best_estimator_
best_C_lasso = lasso_cv.best_params_['logit__C']
best_lambda_lasso = 1 / best_C_lasso
print("Best C for LASSO:", best_C_lasso)
print("Best lambda for LASSO:", best_lambda_lasso)


## QUESTION D

from sklearn.metrics import confusion_matrix

def evaluate_model(model, X_test, y_test, name="model"):
    p_hat = model.predict_proba(X_test)[:, 1]
    y_pred = (p_hat >= 0.5).astype(int)

    cm = confusion_matrix(y_test, y_pred)
    TN, FP, FN, TP = cm.ravel()

    type_I  = FP / (TN + FP) if (TN + FP) > 0 else np.nan
    type_II = FN / (TP + FN) if (TP + FN) > 0 else np.nan
    overall = (FP + FN) / (TP + TN + FP + FN)

    print(f"\n=== {name} ===")
    print("Confusion matrix:\n", cm)
    print(f"Type I error: {type_I:.4f}")
    print(f"Type II error: {type_II:.4f}")
    print(f"Overall error rate: {overall:.4f}")

    return {"confusion_matrix": cm,"type_I": type_I,"type_II": type_II,"overall": overall}

results_plain = evaluate_model(logit_model, X_test, y_test, "Plain Logistic Regression")
results_ridge = evaluate_model(ridge_best, X_test, y_test, "Ridge Logistic Regression")
results_lasso = evaluate_model(lasso_best, X_test, y_test, "LASSO Logistic Regression")


## QUESTION E

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=300,max_depth=None,min_samples_leaf=5,n_jobs=-1,random_state=42)
rf.fit(X_train, y_train)
results_rf = evaluate_model(rf, X_test, y_test, "Random Forest")


## QUESTION F

from sklearn.neural_network import MLPClassifier

mlp_model = Pipeline([('scaler', StandardScaler()),('mlp', MLPClassifier(hidden_layer_sizes=(32, 16),activation='relu',solver='adam',
            alpha=1e-4,max_iter=200,early_stopping=True,n_iter_no_change=10,random_state=42))])
mlp_model.fit(X_train, y_train)
results_mlp = evaluate_model(mlp_model, X_test, y_test, "Neural Network (MLP)")