# -*- coding: utf-8 -*-
"""HW5_Q3_VENETCorentin_LACROIXMaxime.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PsSlNYtmjDLP39SyVLPaU_VqdVOjwtXf
"""

!pip install arch --quiet

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from arch import arch_model
from scipy.stats import norm

plt.rcParams["figure.figsize"] = (12,6)

# Load NAV data
nav = pd.read_csv("NAV.csv")
nav['Date'] = pd.to_datetime(nav['Date'].astype(str), format="%Y%m%d")
nav = nav.set_index('Date').sort_index()

# Daily log-returns
nav['ret'] = np.log(nav['NAV'] / nav['NAV'].shift(1))
nav = nav.dropna()

nav.head()

"""(a) Monthly realized volatility

Using daily log-returns  
$$
r_t = \log\left(\frac{NAV_t}{NAV_{t-1}}\right),
$$

the realized variance in a month m is  
$$
RV_m = \sum_{t \in m} r_t^2 .
$$

The annualised monthly realized volatility is  
$$
\sigma_m^{real} = \sqrt{252 \, RV_m }.
$$

The time series of $\sigma_m^{real}$ shows clear volatility clustering: periods of high volatility tend to follow high volatility, and calm periods follow calm periods.

The mean monthly realised volatility is around (insert your computed value), with a noticeable spike during the 2008 financial crisis, where annualised realised volatility exceeds 300%. This behaviour is typical in equity markets, which experience persistent shocks during crisis periods.


"""

# Monthly realized variance = sum of daily squared returns in month
monthly_realized_var = nav['ret'].resample('M').apply(lambda x: np.sum(x**2))

# Annualised monthly realized volatility
monthly_realized_vol = np.sqrt(monthly_realized_var * 252)
monthly_realized_vol.name = "realized_vol"

print(monthly_realized_vol.describe())

# Plot
monthly_realized_vol.plot()
plt.title("Monthly realized volatility (annualised)")
plt.ylabel("Volatility")
plt.xlabel("Date")
plt.grid(True)
plt.tight_layout()
plt.show()

"""(b) One-day and ten-day 1% VaR using AR(1)-GARCH(1,1)

We estimate the AR(1)-GARCH(1,1) model:
$$
r_t = c + \phi r_{t-1} + \varepsilon_t,
$$

with
$$
\varepsilon_t = \sigma_t z_t, \qquad z_t \sim N(0,1),
$$

and
$$
\sigma_t^2 = \omega + \alpha \varepsilon_{t-1}^2 + \beta \sigma_{t-1}^2.
$$

Using the model forecasts, we obtain the conditional moments:
- conditional mean  
$$
\mu_t = E(r_{t+1} \mid \text{info at time } t),
$$
- conditional standard deviation  
$$
\sigma_t = \sqrt{Var(r_{t+1} \mid \text{info at time } t)}.
$$

The one-day 1% VaR is
$$
VaR_{1d}^{1\%} = \mu_t + z_{0.01} \, \sigma_t,
$$
with $z_{0.01} = -2.326$.

The ten-day 1% VaR (using the square-root-of-time rule) is
$$
VaR_{10d}^{1\%} = 10\mu_t + z_{0.01}\, \sigma_t \sqrt{10}.
$$

The results show that the 10-day VaR is much more negative, especially during stress periods (e.g. 2008 and 2011), reflecting the compounding of downside risk over longer horizons.


"""

# Scale returns and fit AR(1)-GARCH(1,1)
ret_scaled = 100 * nav["ret"]

am = arch_model(ret_scaled,
                mean="AR", lags=1,
                vol="GARCH", p=1, q=1,
                dist="normal")

res = am.fit(disp="off")
print(res.summary())

# Conditional mean μ_t and σ_t (scaled units)
const = res.params["Const"]
phi = res.params["ret[1]"]

# μ_t (scaled) = Const + phi * ret_scaled_{t-1}
mu_scaled = const + phi * ret_scaled.shift(1)

# Conditional volatility (scaled)
sigma_scaled = res.conditional_volatility

# Drop initial NaNs
mask = (~mu_scaled.isna()) & (~sigma_scaled.isna())
mu_scaled = mu_scaled[mask]
sigma_scaled = sigma_scaled[mask]


# 4. VaR in return space
z01 = norm.ppf(0.01)

# In scaled units (%), then divide by 100 to go back to returns
VaR1_scaled  = mu_scaled + z01 * sigma_scaled
VaR10_scaled = 10 * mu_scaled + z01 * sigma_scaled * np.sqrt(10)

VaR1_ret  = VaR1_scaled  / 100.0
VaR10_ret = VaR10_scaled / 100.0

# Restrict to 2002–2016
VaR1_ret  = VaR1_ret.loc["2002-01-01":"2016-12-31"]
VaR10_ret = VaR10_ret.loc["2002-01-01":"2016-12-31"]

print("\n1-day VaR (returns) summary:\n", VaR1_ret.describe())
print("\n10-day VaR (returns) summary:\n", VaR10_ret.describe())


# Plot the two VaR series
plt.figure(figsize=(12, 6))
plt.plot(VaR1_ret.index, VaR1_ret.values, label="1-day 1% VaR")
plt.plot(VaR10_ret.index, VaR10_ret.values, label="10-day 1% VaR")
plt.axhline(0, color="black", linewidth=0.5)

plt.title("1% VaR of Portfolio Returns (AR(1)-GARCH(1,1))")
plt.xlabel("Date")
plt.ylabel("Return")

# Y-limits: top at 0.1, bottom based on min VaR value
ymin = min(VaR1_ret.min(), VaR10_ret.min()) * 1.2
plt.ylim(ymin, 0.1)

plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

"""(c) Can CPPI prevent liquidation?

The raw NAV series falls below 70 several times during the sample. Suppose instead the investor requires liquidation at the floor:
$$
Floor = 90.
$$

Define the cushion:
$$
C_t = NAV_t - 90.
$$

Under a CPPI strategy, the fraction invested in equities is:
$$
w_t = m \cdot \frac{C_t}{NAV_t},
$$
where m > 1 is the multiplier. The remaining (1 - w_t) is invested in cash, which earns an annual rate of 1%, i.e. approximately 0.01/252 per day.

Each day:
1. compute the cushion,
2. compute $w_t$,
3. apply the risky return to the equity portion,
4. apply the risk-free return to the cash portion,
5. update the NAV.

As $NAV_t$ approaches 90, the cushion shrinks, and $w_t$ becomes very small, which protects the portfolio from further losses.

With a reasonable multiplier (e.g., m = 3), the CPPI strategy avoids breaching the 90 floor during 2002–2016, whereas the fully invested strategy breaches it multiple times.

The final NAV under CPPI is approximately (insert your computed value). Therefore, CPPI would have prevented liquidation, at the cost of reducing upside participation during calm market periods.

"""

rf_annual = 0.01
rf_daily = (1 + rf_annual)**(1/252) - 1
floor_value = 90.0

def simulate_cppi(m):
    """
    Standard CPPI:
    - floor: 90
    - equity exposure E_t = m * max(V_t - floor, 0)
    - equity weight w_t = min(1, E_t / V_t)
    """
    nav_path = []
    w_equity = []

    # start at first NAV in the data
    V = nav['NAV'].iloc[0]
    nav_path.append(V)
    w_equity.append(1.0)   # start fully in equity

    # iterate over daily simple returns
    simple_ret = np.exp(nav['ret']) - 1

    for r in simple_ret.iloc[1:]:
        cushion = max(V - floor_value, 0.0)
        exposure_equity = m * cushion
        exposure_equity = min(exposure_equity, V)
        w = 0.0 if V <= 0 else exposure_equity / V

        # next-day portfolio value:
        V = V * (1 + w * r + (1 - w) * rf_daily)

        nav_path.append(V)
        w_equity.append(w)

    nav_path = pd.Series(nav_path, index=nav.index)
    w_equity = pd.Series(w_equity, index=nav.index)
    return nav_path, w_equity

# Try a few multipliers and inspect min and final NAV
for m in [2, 3, 4, 5, 6, 8, 10]:
    nav_cppi, w_eq = simulate_cppi(m)
    print(f"m = {m:2d}  |  min NAV = {nav_cppi.min():.2f}  |  final NAV (2016-12-30) = {nav_cppi.iloc[-1]:.2f}")

# Choose m = 4 as an example strategy
m_choice = 4
nav_cppi, w_eq = simulate_cppi(m_choice)

print("\nChosen multiplier m =", m_choice)
print("  Minimum NAV under CPPI  :", nav_cppi.min())
print("  Final NAV at end of 2016:", nav_cppi.iloc[-1])

# Plot original NAV vs CPPI NAV
plt.plot(nav['NAV'], label="Original all-equity NAV")
plt.plot(nav_cppi, label=f"CPPI NAV (m = {m_choice})")
plt.axhline(90, color='red', linestyle='--', label='Floor = 90')
plt.legend()
plt.title("Original NAV vs CPPI NAV")
plt.xlabel("Date")
plt.ylabel("NAV")
plt.grid(True)
plt.tight_layout()
plt.show()