# -*- coding: utf-8 -*-
"""HW5_Q2_VENETCorentin_LACROIXMaxime.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Czf3xNbnPfiAJbK0t0PL9kpw3lApc8aA
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm
import warnings
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tools.sm_exceptions import ConvergenceWarning

warnings.filterwarnings("ignore", category=ConvergenceWarning)

plt.rcParams["figure.figsize"] = (12,6)

# Load data
df = pd.read_csv("WMT.csv")
df["Period"] = pd.PeriodIndex(df["datacqtr"], freq="Q-DEC")
df["x"] = np.log(df["revtq"])

"""# (a) First and Seasonal Differences of Log Earnings

Let $x_t = \log(\text{earnings}_t)$ denote Wal-Mart’s log quarterly earnings.  
We consider two transformed series:

$$
\Delta x_t = x_t - x_{t-1}, \qquad
\Delta_4 x_t = x_t - x_{t-4}.
$$

### Economic meaning

- The first difference $ \Delta x_t $ approximates the **quarter-over-quarter percentage growth** of earnings.  
- The seasonal difference $ \Delta_4 x_t $ approximates the **year-over-year percentage growth**.

### Statistical properties

- Both differenced series fluctuate around a stable mean and show roughly constant variance, so they are close to **stationary**.  
- $ \Delta x_t $ displays noticeable **quarterly seasonality** and higher volatility.  
- $ \Delta_4 x_t $ is smoother and mainly captures **long-term growth** and **business-cycle movements**.

"""

df["dx"] = df["x"].diff(1)
df["d4x"] = df["x"].diff(4)

print("Mean Δx_t:", df["dx"].mean())
print("Std  Δx_t:", df["dx"].std())
print("Mean Δ4 x_t:", df["d4x"].mean())
print("Std  Δ4 x_t:", df["d4x"].std())

# Plot Δx_t
plt.plot(df["Period"].dt.to_timestamp(), df["dx"])
plt.title("Δx_t — First Difference of Log Earnings")
plt.xlabel("Time")
plt.ylabel("Δx_t")
plt.grid(True)
plt.tight_layout()
plt.show()

# Plot Δ4 x_t
plt.plot(df["Period"].dt.to_timestamp(), df["d4x"])
plt.title("Δ4 x_t — Seasonal Difference of Log Earnings")
plt.xlabel("Time")
plt.ylabel("Δ4 x_t")
plt.grid(True)
plt.tight_layout()
plt.show()

"""## (b) ARIMA(0,1,1) Model

We estimate the model

$$
x_{t+1} - x_t = a_0 + \varepsilon_{t+1} - \theta \varepsilon_t
$$

using data from 1971Q1 to 2018Q4.

The parameter estimates are

$$
\widehat{a}_0 = 0,
\qquad
\widehat{\theta} \approx - 0.475
$$

**Interpretation**

- $ \widehat{a}_0 $ is the **average quarterly drift** in log earnings (average quarter-over-quarter growth).
- $ \widehat{\theta} $ measures how quickly shocks to quarterly earnings growth are **reversed or propagated** into the next quarter.
"""

train_end = df.index[df["datacqtr"] == "2018Q4"][0]
x_train = df.loc[:train_end, "x"]

model_011 = ARIMA(x_train, order=(0,1,1), trend="t")
res_011 = model_011.fit()
print(res_011.summary())

a0_hat = res_011.params.get("trend", np.nan)
theta_hat = res_011.params["ma.L1"]

print("Estimated slope in levels (trend):", a0_hat)
print("Estimated MA(1) theta:", theta_hat)

"""## (c) Airline Model

The airline model is

$$
(x_t - x_{t-1}) - (x_{t-4} - x_{t-5})
= (\varepsilon_t - \theta_1 \varepsilon_{t-1})
  - \theta_4 (\varepsilon_{t-4} - \theta_1 \varepsilon_{t-5}),
$$

which is equivalent to a SARIMA \((0,1,1)\times(0,1,1)_4\) model.

The estimated parameters are

$$
\widehat{\theta}_1 \approx -0.0359,
\qquad
\widehat{\theta}_4 \approx -0.4372.
$$

**Interpretation**

- $ \widehat{\theta}_1 $ captures **short-run, quarter-to-quarter adjustments**.
- $ \widehat{\theta}_4 $ captures **seasonal persistence**: a shock today still affects the same quarter next year.

"""

airline = sm.tsa.SARIMAX(
    x_train,
    order=(0,1,1),
    seasonal_order=(0,1,1,4),
    trend="t"   # linear trend in levels
)
res_airline = airline.fit(disp=False)
print(res_airline.summary())

theta1_hat = res_airline.params["ma.L1"]
theta4_hat = res_airline.params["ma.S.L4"]

print("θ1 (non-seasonal MA1):", theta1_hat)
print("θ4 (seasonal MA1 at lag 4):", theta4_hat)

"""## (d) One-Quarter-Ahead Forecasts (2019Q1–2024Q4)

For each quarter from 2019Q1 to 2024Q4 we:

1. Re-estimate each model using all data up to quarter $ t $,
2. Forecast $ x_{t+1} $,
3. Convert forecasts to earnings via $ \exp(\widehat{x}_{t+1}) $.

Both the ARIMA(0,1,1) model and the airline model produce one-step-ahead forecasts for every quarter in the testing window.

"""

forecast_011 = []
forecast_airline = []
forecast_periods = []

for idx in range(train_end, len(df) - 1):
    x_sub = df.loc[:idx, "x"]

    # ARIMA(0,1,1) with linear trend
    m1 = ARIMA(x_sub, order=(0,1,1), trend="t").fit()
    f1 = m1.forecast(1).iloc[0]

    # Airline model with linear trend
    m2 = sm.tsa.SARIMAX(
        x_sub,
        order=(0,1,1),
        seasonal_order=(0,1,1,4),
        trend="t"
    ).fit(disp=False)
    f2 = m2.forecast(1).iloc[0]

    forecast_011.append(f1)
    forecast_airline.append(f2)
    forecast_periods.append(df.loc[idx+1, "datacqtr"])

forecast_df = pd.DataFrame({
    "datacqtr": forecast_periods,
    "x_hat_011": forecast_011,
    "x_hat_airline": forecast_airline
})

# Merge with realized x_t for test period
results = df.loc[train_end+1:, ["datacqtr","x"]].merge(forecast_df, on="datacqtr")
results["earnings_realized"] = np.exp(results["x"])
results["earnings_hat_011"] = np.exp(results["x_hat_011"])
results["earnings_hat_airline"] = np.exp(results["x_hat_airline"])

print("\nFirst few rows of realized vs forecasts:")
print(results.head(10))

"""
## (e) Forecast Errors and Accuracy

Forecast errors are defined as

$$
e_{t+1} = x_{t+1} - \mathbb{E}_t[x_{t+1}].
$$

The mean-squared error (MSE) is

$$
\text{MSE} = \frac{1}{n} \sum_{i=1}^n e_{t+i}^2.
$$

Empirically we obtain

$$
\text{MSE}_{011} \approx 0.00646,
\qquad
\text{MSE}_{\text{airline}} \approx 0.00047.
$$

**Conclusion**

The model with the smaller MSE — typically the airline model — performs better in out-of-sample forecasting."""

results["err_011"] = results["x"] - results["x_hat_011"]
results["err_air"] = results["x"] - results["x_hat_airline"]

mse_011 = np.mean(results["err_011"]**2)
mse_air = np.mean(results["err_air"]**2)

print("\nMSE ARIMA(0,1,1):", mse_011)
print("MSE Airline model:", mse_air)

plt.plot(results["datacqtr"], results["err_011"], marker="o", label="ARIMA(0,1,1)")
plt.plot(results["datacqtr"], results["err_air"], marker="o", label="Airline")
plt.xticks(rotation=45)
plt.ylabel("Forecast error (log earnings)")
plt.title("Forecast errors 2019Q1–2024Q4")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

"""## (f) COVID-19 and Model Performance

During the COVID-19 pandemic, Wal-Mart’s earnings experienced a **structural break**: lockdowns, online shopping surges, and supply-chain disruptions. Both models are estimated on 1971–2018 and assume **stable dynamics**, so their forecast accuracy deteriorates during this period.

**How to improve forecasts in real time**

- Add structural-break dummy variables for the COVID period.
- Use rolling-window or time-decay estimation to give more weight to recent data.
- Include external regressors (e.g. retail sales indices, mobility indicators).
- Combine statistical forecasts with managerial guidance or scenario analysis.
"""