# -*- coding: utf-8 -*-
"""Project2_FinancialEngineering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ki2iK-NciyJUT8J87YArlf2SpK00OWOf
"""

## QUESTION 1

import numpy as np
import math

S0 = 100
K = 100
r = 0.05
sigma = 0.25
T = 22/252
gamma = 1.0
lam = 0.0005

N_days = 22
steps_per_day = 10
N = N_days * steps_per_day
dt = T / N

u = np.exp(sigma * np.sqrt(dt))
d = 1/u
p = (np.exp(r*dt) - d) / (u - d)
R = np.exp(r*dt)

# binomial tree
S_tree = np.full((N+1, N+1), np.nan)
S_tree[0, 0] = S0
for n in range(1, N+1):
    for j in range(n+1):
        S_tree[n, j] = S0 * (u**j) * (d**(n-j))

## QUESTION 2

import matplotlib.pyplot as plt
from scipy.stats import norm

# grid of possible stock positions
theta_min, theta_max = -1.0, 1.0
N_theta = 21
theta_grid = np.linspace(theta_min, theta_max, N_theta)
theta0_index = np.argmin(np.abs(theta_grid - 0.0))


alpha = np.array([R**(N-n) for n in range(N+1)])


def transaction_cost(S, theta_old, theta_new, lam):
    delta = theta_new - theta_old
    if delta > 0:   # buy
        return (1 + lam) * S * delta
    elif delta < 0: # sell
        return (1 - lam) * S * delta
    else:
        return 0.0

def liquidation_value(S, theta, lam):
    if theta > 0:   # sell long
        return (1 - lam) * S * theta
    elif theta < 0: # buy back short
        return (1 + lam) * S * theta
    else:
        return 0.0


H = [None]*(N+1)
policy = [None]*(N+1)

# terminal condition at N
H_N = np.zeros((N+1, N_theta))
for j in range(N+1):
    S_T = S_tree[N, j]
    payoff = max(S_T - K, 0.0)
    for i, theta in enumerate(theta_grid):
        L = liquidation_value(S_T, theta, lam)
        H_N[j, i] = np.exp(-gamma * (L - payoff))
H[N] = H_N
policy[N] = np.zeros((N+1, N_theta), dtype=int)


# backward induction
for n in range(N-1, -1, -1):
    H_n = np.zeros((n+1, N_theta))
    pol_n = np.zeros((n+1, N_theta), dtype=int)
    alpha_n = alpha[n]
    H_next = H[n+1]

    for j in range(n+1):
        S = S_tree[n, j]
        for i, theta in enumerate(theta_grid):
            best_val = np.inf
            best_k = 0

            for k, theta_new in enumerate(theta_grid):
                TC = transaction_cost(S, theta, theta_new, lam)
                H_up = H_next[j+1, k]
                H_dn = H_next[j,   k]
                cont = p * H_up + (1-p) * H_dn

                val = np.exp(gamma * alpha_n * TC) * cont

                if val < best_val:
                    best_val = val
                    best_k = k

            H_n[j, i] = best_val
            pol_n[j, i] = best_k

    H[n] = H_n
    policy[n] = pol_n


def bs_delta_call(S, K, T, r, sigma):
    if T <= 0:
        return 1.0 if S > K else 0.0
    d1 = (np.log(S/K) + (r + 0.5*sigma**2)*T) / (sigma*np.sqrt(T))
    return norm.cdf(d1)

def plot_hedge_vs_price(times):
    plt.figure(figsize=(8, 5))
    for n in times:
        S_nodes = S_tree[n, :n+1]
        theta_star = np.zeros(n+1)
        for j in range(n+1):
            k_star = policy[n][j, theta0_index]
            theta_star[j] = theta_grid[k_star]

        plt.plot(S_nodes, theta_star, marker='o', linestyle='-', label=f"time step n={n}")

    for n in times:
        t = n*dt
        tau = T - t
        S_nodes = S_tree[n, :n+1]
        delta_nodes = [bs_delta_call(S, K, tau, r, sigma) for S in S_nodes]
        plt.plot(S_nodes, delta_nodes, linestyle='--', label=f"BS delta n={n}")

    plt.axhline(0.0, linestyle=':', linewidth=1)
    plt.xlabel("Stock price S")
    plt.ylabel("Optimal target holding θ*")
    plt.title("Optimal hedging policy θ*(S) vs BSM delta (starting from θ=0)")
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.show()

# plots
plot_hedge_vs_price([0, N//2, N-1])


def plot_no_trade_region(n):
    S_nodes = S_tree[n, :n+1]
    M = np.zeros((N_theta, n+1))

    for j in range(n+1):
        for i in range(N_theta):
            k_star = policy[n][j, i]
            # no trade if target holding == current holding
            M[i, j] = 1.0 if k_star == i else 0.0

    plt.figure(figsize=(8, 5))
    extent = [S_nodes[0], S_nodes[-1], theta_min, theta_max]
    plt.imshow(M, origin='lower', aspect='auto', extent=extent)
    plt.colorbar(label="1 = no trade, 0 = trade")
    plt.xlabel("Stock price S")
    plt.ylabel("Current holding θ")
    plt.title(f"No-trade region at time step n={n}")
    plt.tight_layout()
    plt.show()

# plot
plot_no_trade_region(N//2)

## QUESTION 3

alpha0 = R**N
H0_S0_theta0 = H[0][0, theta0_index]

W0_indiff = np.log(H0_S0_theta0) / (gamma * alpha0)
print("Indifference price W0 (with transaction costs):", W0_indiff)

from math import log, sqrt, exp

def bs_call_price(S, K, r, sigma, T):
    if T <= 0:
        return max(S - K, 0.0)
    d1 = (log(S / K) + (r + 0.5 * sigma**2) * T) / (sigma * sqrt(T))
    d2 = d1 - sigma * sqrt(T)
    return S * norm.cdf(d1) - K * exp(-r * T) * norm.cdf(d2)

sigma_ref = 0.25 # "true" vol in GBM
C_bs_nocost = bs_call_price(S0, K, r, sigma_ref, T)
print("Frictionless BS call price (σ = 0.25):", C_bs_nocost)


def implied_vol_call(target_price, S, K, r, T, sigma_low=1e-4, sigma_high=3.0, tol=1e-6, max_iter=100):
    """Bisection implied vol for a European call."""
    for _ in range(max_iter):
        mid = 0.5 * (sigma_low + sigma_high)
        price_mid = bs_call_price(S, K, r, mid, T)
        if abs(price_mid - target_price) < tol:
            return mid
        if price_mid > target_price:
            sigma_high = mid
        else:
            sigma_low = mid
    return 0.5 * (sigma_low + sigma_high)

# for the frictionless BS price, implied vol is the input vol:
sigma_imp_nocost = implied_vol_call(C_bs_nocost, S0, K, r, T)
print("Implied vol (no transaction costs):", sigma_imp_nocost)

# implied vol corresponding to indifference price
sigma_imp_indiff = implied_vol_call(W0_indiff, S0, K, r, T)
print("Implied vol (indifference price W0):", sigma_imp_indiff)

## QUESTION 4

rng = np.random.default_rng(123)

def simulate_optimal_hedge(M, W0, policy, theta_grid):
    tracking_errors = np.zeros(M)
    intervals_all = []

    for m in range(M):
        W = W0
        theta_idx = theta0_index
        theta = theta_grid[theta_idx]
        j = 0
        last_trade_time = 0

        for n in range(N):
            S = S_tree[n, j]

            # optimal new position given (n, node j, current theta_idx)
            k_star = policy[n][j, theta_idx]
            theta_new = theta_grid[k_star]

            # record a trade and its time gap
            if k_star != theta_idx:
                intervals_all.append(n - last_trade_time)
                last_trade_time = n

            # transact and pay/receive TC
            TC = transaction_cost(S, theta, theta_new, lam)
            W -= TC

            # cash accrues at risk-free rate to next time step
            W *= R

            # update state
            theta_idx = k_star
            theta = theta_new

            # stock move (risk-neutral)
            if rng.random() < p:
                j += 1

        # at maturity: liquidate and compute tracking error
        S_T = S_tree[N, j]
        L = liquidation_value(S_T, theta, lam)
        W_T = W + L
        payoff = max(S_T - K, 0.0)
        tracking_errors[m] = W_T - payoff

    return tracking_errors, np.array(intervals_all)


# base price
W0_base = W0_indiff

# simulated paths
M = 50000
te, intervals = simulate_optimal_hedge(M, W0_base, policy, theta_grid)

mean_te = te.mean()
std_te = te.std(ddof=1)
print("Mean tracking error:", mean_te)
print("Std of tracking error:", std_te)

# Histogram + Gaussian overlay
plt.figure(figsize=(8, 5))
plt.hist(te, bins=100, density=True, alpha=0.7, edgecolor='none', label="Simulated TE")

xs = np.linspace(mean_te - 4*std_te, mean_te + 4*std_te, 300)
normal_pdf = (1/(std_te*np.sqrt(2*np.pi)) * np.exp(-0.5*((xs-mean_te)/std_te)**2))
plt.plot(xs, normal_pdf, linewidth=2, label="Gaussian with same mean/std")

plt.xlabel("Tracking error  WT - max(ST - K, 0)")
plt.ylabel("Density")
plt.title("Distribution of tracking error under optimal hedging")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()


def solve_dp_for_gamma(gamma):
    """
    Re-run the DP for a given risk-aversion gamma.
    Returns (H, policy).
    Uses all global objects: S_tree, theta_grid, etc.
    """
    # precompute alpha_n
    alpha = np.array([R**(N-n) for n in range(N+1)])

    H = [None]*(N+1)
    policy = [None]*(N+1)

    # terminal condition
    H_N = np.zeros((N+1, N_theta))
    for j in range(N+1):
        S_T = S_tree[N, j]
        payoff = max(S_T - K, 0.0)
        for i, theta in enumerate(theta_grid):
            L = liquidation_value(S_T, theta, lam)
            H_N[j, i] = np.exp(-gamma * (L - payoff))
    H[N] = H_N
    policy[N] = np.zeros((N+1, N_theta), dtype=int)

    # backward induction (MINIMIZE val)
    for n in range(N-1, -1, -1):
        H_n = np.zeros((n+1, N_theta))
        pol_n = np.zeros((n+1, N_theta), dtype=int)
        alpha_n = alpha[n]
        H_next = H[n+1]

        for j in range(n+1):
            S = S_tree[n, j]
            for i, theta in enumerate(theta_grid):
                best_val = np.inf
                best_k = 0
                for k, theta_new in enumerate(theta_grid):
                    TC = transaction_cost(S, theta, theta_new, lam)
                    H_up = H_next[j+1, k]
                    H_dn = H_next[j,   k]
                    cont = p*H_up + (1-p)*H_dn
                    val = np.exp(gamma * alpha_n * TC) * cont
                    if val < best_val:
                        best_val = val
                        best_k = k
                H_n[j, i] = best_val
                pol_n[j, i] = best_k

        H[n] = H_n
        policy[n] = pol_n

    return H, policy


gammas = [0.1, 0.3, 0.5, 1.0, 2.0, 5.0]
mean_list = []
std_list = []

W0_base = C_bs_nocost
M_small = 10000

for g in gammas:
    print("Solving DP for gamma =", g)
    H_g, policy_g = solve_dp_for_gamma(g)
    te_g, _ = simulate_optimal_hedge(M_small, W0_base, policy_g, theta_grid)
    mean_list.append(te_g.mean())
    std_list.append(te_g.std(ddof=1))

# plot mean vs std
plt.figure(figsize=(7, 5))
plt.plot(std_list, mean_list, marker='o')
for g, x, y in zip(gammas, std_list, mean_list):
    plt.annotate(f"γ={g}", (x, y), textcoords="offset points", xytext=(5,5))

plt.xlabel("Std of tracking error")
plt.ylabel("Mean tracking error")
plt.title("Mean–Std trade-off of tracking error as γ varies")
plt.grid(True)
plt.tight_layout()
plt.show()

print("Average gap between trades (in time steps):", intervals.mean())
print("Median gap:", np.median(intervals))
print("10th/90th percentile gaps:", np.quantile(intervals, [0.1, 0.9]))

max_gap = int(intervals.max())
bins = np.arange(1, max_gap+2) - 0.5

plt.figure(figsize=(8, 5))
plt.hist(intervals, bins=bins, density=True, edgecolor='black')
plt.xticks(range(1, max_gap+1))
plt.xlabel("Number of periods between successive trades")
plt.ylabel("Probability")
plt.title("Distribution of inter-trade times under optimal strategy")
plt.grid(True, axis='y')
plt.tight_layout()
plt.show()

## QUESTION 5

rng = np.random.default_rng(123)

def simulate_heuristic_delta(M, W0, rebalance_every_steps):
    """
    Heuristic strategy: rebalance to BSM delta every 'rebalance_every_steps' time steps.
    Returns array of tracking errors of length M.
    """
    tracking_errors = np.zeros(M)

    for m in range(M):
        W = W0
        theta = 0.0
        j = 0

        for n in range(N):
            S = S_tree[n, j]

            # re-hedge only at fixed intervals (including time 0)
            if n % rebalance_every_steps == 0:
                tau = T - n*dt
                delta = bs_delta_call(S, K, tau, r, sigma)
                theta_new = delta

                TC = transaction_cost(S, theta, theta_new, lam)
                W -= TC
                theta = theta_new

            # risk-free growth of cash until next step
            W *= R

            # stock move (binomial under Q)
            if rng.random() < p:
                j += 1

        # at maturity: liquidate and compute tracking error
        S_T = S_tree[N, j]
        L = liquidation_value(S_T, theta, lam)
        W_T = W + L
        payoff = max(S_T - K, 0.0)
        tracking_errors[m] = W_T - payoff

    return tracking_errors


M = 50000
W0 = W0_indiff

# optimal strategy (from Q4)
te_opt, _ = simulate_optimal_hedge(M, W0, policy, theta_grid)

# heuristic: rebalance once per day (k = 10 steps)
k_day = 10
te_heur_day = simulate_heuristic_delta(M, W0, k_day)

def stats(label, te):
    mean = te.mean()
    std  = te.std(ddof=1)
    EU   = (-np.exp(-gamma*te)).mean()   # expected utility
    print(f"{label}: mean={mean:.4f}, std={std:.4f}, EU={EU:.6f}")

stats("Optimal", te_opt)
stats("Heuristic (daily)", te_heur_day)

plt.figure(figsize=(8,5))
plt.hist(te_opt, bins=100, density=True, alpha=0.5, label="Optimal")
plt.hist(te_heur_day, bins=100, density=True, alpha=0.5, label="Heuristic daily")
plt.xlabel("Tracking error")
plt.ylabel("Density")
plt.title("Optimal vs heuristic delta hedging")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()


# rebalancing intervals
k_list = [1, 2, 5, 10, 20, 50]
M_freq = 20000
results = []

for k in k_list:
    te_h = simulate_heuristic_delta(M_freq, W0, k)
    mean = te_h.mean()
    std  = te_h.std(ddof=1)
    EU   = (-np.exp(-gamma*te_h)).mean()
    results.append((k, mean, std, EU))
    print(f"k={k:2d}: mean={mean:.4f}, std={std:.4f}, EU={EU:.6f}")

# choose k that maximizes expected utility
results_sorted = sorted(results, key=lambda x: x[3], reverse=True)
k_best, mean_best, std_best, EU_best = results_sorted[0]
print("\nBest heuristic frequency (by expected utility):")
print(f"  rebalance every {k_best} steps "
      f"(≈ {k_best/steps_per_day:.2f} days), "
      f"mean={mean_best:.4f}, std={std_best:.4f}, EU={EU_best:.6f}")

stds = [s for (_, _, s, _) in results]
means = [m for (_, m, _, _) in results]

plt.figure(figsize=(7,5))
plt.plot(stds, means, marker='o')
for (k, m, s, _) in results:
    plt.annotate(f"k={k}", (s, m), textcoords="offset points", xytext=(5,5))
plt.xlabel("Std of tracking error")
plt.ylabel("Mean tracking error")
plt.title("Heuristic strategy: mean–std vs rebalancing interval k")
plt.grid(True)
plt.tight_layout()
plt.show()

## QUESTION 6

def solve_dp(gamma, K, lam):
    alpha = np.array([R**(N-n) for n in range(N+1)])

    H = [None]*(N+1)
    policy = [None]*(N+1)

    # terminal condition
    H_N = np.zeros((N+1, N_theta))
    for j in range(N+1):
        S_T = S_tree[N, j]
        payoff = max(S_T - K, 0.0)
        for i, theta in enumerate(theta_grid):
            L = liquidation_value(S_T, theta, lam)
            H_N[j, i] = np.exp(-gamma * (L - payoff))
    H[N] = H_N
    policy[N] = np.zeros((N+1, N_theta), dtype=int)

    # backward induction
    for n in range(N-1, -1, -1):
        H_n = np.zeros((n+1, N_theta))
        pol_n = np.zeros((n+1, N_theta), dtype=int)
        alpha_n = alpha[n]
        H_next = H[n+1]

        for j in range(n+1):
            S = S_tree[n, j]
            for i, theta in enumerate(theta_grid):
                best_val = np.inf
                best_k = 0
                for k, theta_new in enumerate(theta_grid):
                    TC = transaction_cost(S, theta, theta_new, lam)
                    H_up = H_next[j+1, k]
                    H_dn = H_next[j,   k]
                    cont = p*H_up + (1-p)*H_dn
                    val = np.exp(gamma * alpha_n * TC) * cont
                    if val < best_val:
                        best_val = val
                        best_k = k
                H_n[j, i] = best_val
                pol_n[j, i] = best_k

        H[n] = H_n
        policy[n] = pol_n

    return H, policy


def indifference_price(H, gamma):
    alpha0 = R**N
    H0 = H[0][0, theta0_index]
    return np.log(H0) / (gamma * alpha0)



def simulate_optimal_hedge(M, W0, policy, theta_grid, K, lam):
    tracking_errors = np.zeros(M)
    intervals_all = []

    for m in range(M):
        W = W0
        theta_idx = theta0_index
        theta = theta_grid[theta_idx]
        j = 0
        last_trade_time = 0

        for n in range(N):
            S = S_tree[n, j]

            k_star = policy[n][j, theta_idx]
            theta_new = theta_grid[k_star]
            if k_star != theta_idx:
                intervals_all.append(n - last_trade_time)
                last_trade_time = n

            TC = transaction_cost(S, theta, theta_new, lam)
            W -= TC
            W *= R

            theta_idx = k_star
            theta = theta_new

            if rng.random() < p:
                j += 1

        S_T = S_tree[N, j]
        L = liquidation_value(S_T, theta, lam)
        W_T = W + L
        payoff = max(S_T - K, 0.0)
        tracking_errors[m] = W_T - payoff

    return tracking_errors, np.array(intervals_all)


gamma_base = 1.0
K_list = [100, 110, 120]
lam_list = [0.0, 0.0005, 0.001, 0.002]
M = 20000

results = []

for K_val in K_list:
    for lam_val in lam_list:
        print(f"Solving DP for K={K_val}, λ={lam_val}")
        H_KL, policy_KL = solve_dp(gamma_base, K_val, lam_val)
        W0_KL = indifference_price(H_KL, gamma_base)

        te_KL, ints_KL = simulate_optimal_hedge(M, W0_KL, policy_KL, theta_grid,
                                                K_val, lam_val)
        mean_TE = te_KL.mean()
        std_TE  = te_KL.std(ddof=1)
        EU      = (-np.exp(-gamma_base * te_KL)).mean()
        avg_trades = len(ints_KL) / M

        results.append((K_val, lam_val, W0_KL, mean_TE, std_TE, EU, avg_trades))
        print(f"  W0={W0_KL:.4f}, mean={mean_TE:.4f}, std={std_TE:.4f}, "
              f"EU={EU:.6f}, avg trades≈{avg_trades:.2f}")


import pandas as pd

df = pd.DataFrame(results, columns=["K", "lam", "W0", "mean", "std", "EU", "avg_trades"])

plt.figure(figsize=(7,5))
for K_val in K_list:
    sub = df[df["K"] == K_val]
    plt.plot(sub["lam"], sub["W0"], marker='o', label=f"K={K_val}")
plt.xlabel("Transaction cost λ")
plt.ylabel("Indifference price W0")
plt.title("Indifference option price vs transaction cost")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()


plt.figure(figsize=(7,5))
for K_val in K_list:
    sub = df[df["K"] == K_val]
    plt.plot(sub["lam"], sub["std"], marker='o', label=f"K={K_val}")
plt.xlabel("λ")
plt.ylabel("Std of tracking error")
plt.title("Std(TE) vs transaction cost λ")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

plt.figure(figsize=(7,5))
for K_val in K_list:
    sub = df[df["K"] == K_val]
    plt.plot(sub["lam"], sub["mean"], marker='o', label=f"K={K_val}")
plt.xlabel("λ")
plt.ylabel("Mean tracking error")
plt.title("Mean(TE) vs transaction cost λ")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()


plt.figure(figsize=(7,5))
for K_val in K_list:
    sub = df[df["K"] == K_val]
    plt.plot(sub["lam"], sub["avg_trades"], marker='o', label=f"K={K_val}")
plt.xlabel("λ")
plt.ylabel("Average number of trades per path")
plt.title("Trading intensity vs λ")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()