# -*- coding: utf-8 -*-
"""15_433_HW5_pythoncode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yhiaCHkIchJIT9wU9x5Et86qrmuBHDtN
"""

import pandas as pd
import numpy as np

## QUESTION A

# Load data
sp500 = pd.read_excel('SPPerformanceGraphExport.xlsx')
spworld = pd.read_excel('SPWorldPerformanceGraphExport.xlsx')
ustreasury = pd.read_excel('USTreasuryPerformanceGraphExport.xlsx')
rf = pd.read_excel('DTB4WK.xlsx')

# Clean index data
def clean_index(df):
    df = df.iloc[:, :2]
    df.columns = ['Date','Value']
    df = df.dropna()
    df['Date'] = pd.to_datetime(df['Date'], errors='coerce')
    df = df.dropna()
    df = df.set_index('Date')
    return df

sp500_c = clean_index(sp500)
spworld_c = clean_index(spworld)
ustreasury_c = clean_index(ustreasury)


## QUESTION B

# Compute returns
rets = pd.concat([
    sp500_c['Value'].pct_change(),
    spworld_c['Value'].pct_change(),
    ustreasury_c['Value'].pct_change()
], axis=1)

rets.columns = ['SP500','SPWorld','USTreasury']

# Risk-free rate conversion
rf['observation_date'] = pd.to_datetime(rf['observation_date'])
rf = rf.set_index('observation_date')['DTB4WK']/100/252

rets = rets.dropna()
rf_aligned = rf.reindex(rets.index).fillna(method='ffill')
excess = rets.sub(rf_aligned, axis=0)

# Annualised mean and covariance
mu = excess.mean()*252
Sigma = excess.cov()*252

# Market weights and BL prior
delta = 2.5
tau = 0.05
w_mkt = np.array([60,60,30]) / 150
pi = delta * Sigma.values @ w_mkt


## QUESTION C

# View specification
P = np.array([[1,-1,0]])
Q = np.array([0.02])
Omega = np.array([[0.0005]])

# Posterior calculation
Sigma_bl = np.linalg.inv(np.linalg.inv(tau*Sigma.values) + P.T @ np.linalg.inv(Omega) @ P)
mu_bl = Sigma_bl @ (np.linalg.inv(tau*Sigma.values) @ pi + P.T @ np.linalg.inv(Omega) @ Q)


## QUESTION D

# Portfolio weights prior and posterior
w_prior = (1/delta) * np.linalg.inv(Sigma.values) @ pi
w_BL = (1/delta) * np.linalg.inv(Sigma.values) @ mu_bl

print(mu)
print(Sigma)
print(pi)
print(Sigma_bl)
print(mu_bl)
print(w_prior)
print(w_BL)